"""Fail-closed paths for files named by an untrusted Paperless manifest."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path, PurePosixPath, PureWindowsPath

from .errors import UnsafeOutputError


def _context(document_id: int | str, field: str) -> str:
    return f"document {document_id} {field}"


@dataclass(frozen=True)
class ExportRoot:
    """Canonical export boundary used by every manifest-derived operation."""

    path: Path

    @classmethod
    def from_path(cls, path: Path) -> ExportRoot:
        try:
            return cls(path.resolve(strict=True))
        except OSError as exc:
            raise UnsafeOutputError(
                f"Cannot establish the export-root boundary: {exc.strerror or type(exc).__name__}."
            ) from exc

    def _assert_beneath(self, candidate: Path, *, context: str) -> Path:
        try:
            resolved = candidate.resolve(strict=False)
            resolved.relative_to(self.path)
        except (OSError, ValueError) as exc:
            raise UnsafeOutputError(
                f"Unsafe output path in {context}: it resolves outside the export directory."
            ) from exc
        return resolved

    def confine(
        self,
        value: object,
        *,
        document_id: int | str,
        field: str,
    ) -> ConfinedPath:
        """Validate a manifest value without ever echoing the untrusted value."""
        context = _context(document_id, field)
        if not isinstance(value, str) or not value or "\x00" in value:
            raise UnsafeOutputError(f"Unsafe output path in {context}: path is empty or malformed.")

        posix = PurePosixPath(value)
        windows = PureWindowsPath(value)
        if posix.is_absolute() or windows.is_absolute() or windows.drive:
            raise UnsafeOutputError(
                f"Unsafe output path in {context}: absolute paths are forbidden."
            )

        # Paperless exports POSIX-style paths. Treat backslashes as separators
        # while validating so Windows traversal/UNC spellings cannot become
        # harmless-looking file names on a POSIX host.
        parts = value.replace("\\", "/").split("/")
        if any(part in {"", ".", ".."} for part in parts):
            raise UnsafeOutputError(
                f"Unsafe output path in {context}: empty, current, and parent components "
                "are forbidden."
            )

        relative = Path(*parts)
        self._assert_beneath(self.path / relative, context=context)
        return ConfinedPath(self, relative, context)

    def generated(self, relative: Path, *, context: str) -> ConfinedPath:
        """Confine a path generated by the wrapper under this root."""
        if relative.is_absolute() or any(part in {"", ".", ".."} for part in relative.parts):
            raise UnsafeOutputError(f"Unsafe generated path for {context}.")
        self._assert_beneath(self.path / relative, context=context)
        return ConfinedPath(self, relative, context)


@dataclass(frozen=True)
class ConfinedPath:
    """A relative path whose syntax and current resolution are root-confined."""

    root: ExportRoot
    relative: Path
    context: str

    @property
    def display(self) -> str:
        return self.relative.as_posix()

    def checked(self) -> Path:
        """Repeat confinement immediately before an operation."""
        return self.root._assert_beneath(self.root.path / self.relative, context=self.context)

    def regular_file(self) -> Path | None:
        """Return the rechecked path only when it currently names a regular file."""
        path = self.checked()
        try:
            return path if path.is_file() else None
        except OSError as exc:
            raise UnsafeOutputError(
                f"Cannot inspect confined path for {self.context}: "
                f"{exc.strerror or type(exc).__name__}."
            ) from exc

    def identities(self) -> frozenset[tuple[int, int] | Path]:
        """Path and inode identities, captured before a destructive rewrite."""
        path = self.checked()
        try:
            stat = path.stat()
        except OSError:
            return frozenset({path})
        return frozenset({path, (stat.st_dev, stat.st_ino)})

    def relative_target_from(self, directory: Path) -> Path:
        return Path(os.path.relpath(self.checked(), start=directory))
